		["Mob Health & Armor"."Small Mobs".Clot]
			#Determines max health value of Clots
			"Clot Health" = 20.0
			#Determines armor value of Clots
			"Clot Armor" = 0.0
			#Determines attack damage of Clots
			"Clot Damage" = 4.0
			#Determines move speed of Clots
			"Clot Speed" = 0.25

		["Mob Health & Armor"."Small Mobs".Cyst]
			#Determines max health value of Cysts
			"Cyst Health" = 15.0
			#Determines armor value of Cysts
			"Cyst Armor" = 0.0
			#Determines attack damage of Cysts
			"Cyst Damage" = 4.0
			#Determines move speed of Cysts
			"Cyst Speed" = 0.2

		["Mob Health & Armor"."Small Mobs".Gorefast]
			#Determines max health value of Gorefasts
			"Gorefast Health" = 30.0
			#Determines armor value of Gorefasts
			"Gorefast Armor" = 3.0
			#Determines attack damage of Gorefasts
			"Gorefast Damage" = 5.0
			#Determines move speed of Gorefasts
			"Gorefast Speed" = 0.25
			#Speed Potion Level that applies on Gorefasts when they're sprinting
			" Speed Potion Level when Sprinting" = 1.0

		["Mob Health & Armor"."Small Mobs".Crawler]
			#Determines max health value of Crawlers
			"Crawler Health" = 15.0
			#Determines armor value of Crawlers
			"Crawler Armor" = 2.0
			#Determines attack damage of Crawlers
			"Crawler Damage" = 3.0
			#Determines move speed of Crawlers
			"Crawler Speed" = 0.3

		["Mob Health & Armor"."Small Mobs".Stalker]
			#Determines max health value of Stalkers
			"Stalker Health" = 20.0
			#Determines armor value of Stalkers
			"Stalker Armor" = 0.0
			#Determines attack damage of Stalkers
			"Stalker Damage" = 4.0
			#Determines move speed of Stalkers
			"Stalker Speed" = 0.3

		["Mob Health & Armor"."Medium Mobs".Bloat]
			#Determines max health value of Bloats
			"Bloat Health" = 80.0
			#Determines armor value of Bloat
			"Bloat Armor" = 15.0
			#Determines spit damage of Bloats
			"Spit Damage" = 1.0
			#Determines move speed of Bloats
			"Bloat Speed" = 0.15

		["Mob Health & Armor"."Medium Mobs".Husk]
			#Determines max health value of Husks
			"Husk Health" = 75.0
			#Determines armor value of Husks
			"Husk Armor" = 10.0
			#Determines attack damage of Husks
			"Husk Melee Damage" = 3.0
			#Determines move speed of Husks
			"Husk Speed" = 0.15

		["Mob Health & Armor"."Medium Mobs".Siren]
			#Determines max health value of Sirens
			"Siren Health" = 50.0
			#Determines armor value of Sirens
			"Siren Armor" = 0.0
			#Determines attack damage (of each ticks) of Sirens
			"Melee Bite Damage" = 2.0
			#Determines scream damage (of each ticks) of Sirens
			"Scream Damage" = 2.0
			#Determines move speed of Sirens
			"Siren Speed" = 0.1

		["Mob Health & Armor"."Large Mobs".Scrake]
			#Determines max health value of Scrake
			"Scrake Health" = 250.0
			#Determines armor value of Scrake
			"Scrake Armor" = 10.0
			#Determines damage (of each ticks) of Scrakes' stab attack
			"Chainsaw Stab Damage" = 4.0
			#Determines damage (of each ticks) of Scrakes' slash attack
			"Chainsaw Slash Damage" = 8.0
			#Determines move speed of Scrakes
			"Scrake Speed" = 0.25
			#Speed Potion Level that applies on Scrakes when they're sprinting
			" Speed Potion Level when Sprinting" = 1.0

		["Mob Health & Armor"."Large Mobs".Fleshpound]
			#Determines max health value of Fleshpound
			"Fleshpound Health" = 300.0
			#Determines armor value of Fleshpound
			"Fleshpound Armor" = 45.0
			#Determines damage (of each ticks) of Fleshpound's rage ground pound
			"Rage Ground Pound Damage" = 2.0
			#Determines damage applied when Fleshpound slams into another entity
			"Slam Damage" = 12.0
			#Determines move speed of Fleshpounds
			"Fleshpound Speed" = 0.25
			#Speed Potion Level that applies on Fleshpounds when they're sprinting
			" Speed Potion Level when Sprinting" = 2.0
